//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS3ISP9_14.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StuffList
    {
        public int IDStuffList { get; set; }
        public int IDStuff { get; set; }
        public int IDCheck { get; set; }
        public int Quantity { get; set; }
    
        public virtual Check Check { get; set; }
        public virtual Stuff Stuff { get; set; }
    }
}
