//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS3ISP9_14.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_LevelDiscountGuest
    {
        public string Имя { get; set; }
        public string Телефон { get; set; }
        public string Пол { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public string Почта { get; set; }
        public string Скидочный_код { get; set; }
        public decimal Баланс_балов { get; set; }
        public string Уровень_скидки { get; set; }
    }
}
