//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS3ISP9_14.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_TheBiggestGuest
    {
        public string Имя { get; set; }
        public string Телефон { get; set; }
        public string Уровень_скидки { get; set; }
        public decimal Доступные_баллы { get; set; }
        public Nullable<int> Количество_заказов { get; set; }
    }
}
